# Generated by Django 3.2.25 on 2024-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
