# Generated by Django 3.2.25 on 2024-08-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_library_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='return_date',
        ),
    ]
